### ISSUE TITLE
k2   4.1号 版本 v2ray gfw 模式 不能使用. 

### ISSUE THREAD

**Issue by DestinyHunter** [HuaZhuangNan/actions-build-padavan-openwrt#11]
fork 你的仓库 自己编译出来的只有5m,不知道哪里不对 只改了 lan ip
![image](https://user-images.githubusercontent.com/20897838/85491923-eec26e00-b606-11ea-95b3-29a06b4f6ff2.png)

**Comment by huazhuangnan** [comment]
看下那些软件，这个需要自己设置的！
