### ISSUE TITLE
新编译的固件无法登陆后台

### ISSUE THREAD

**Issue by lon91ong** [HuaZhuangNan/actions-build-padavan-openwrt#17]
看编译日志, 修改用户名密码的脚本似乎并没有报错
![编译日志](https://user-images.githubusercontent.com/16462258/114141454-2d31db00-9944-11eb-9dfa-1672c48631e7.png)

DHCP得到的网段也不是脚本设置的`192.168.3`, 而是`192.168.11`
试过了`admin/admin`, `root/password`, `root/admin`等常用组合都不对

请解惑

**Comment by huazhuangnan** [comment]
固件是真实更新替换了的吗？

**Comment by lon91ong** [comment]
> 固件是真实更新替换了的吗？

用breed更新的, 不是在固件页面更新的
原来用的是OpenWrt固件

由于我的K2硬改过, 16+256+USB的配置, 所以在`PSG1218.config`中开启USB支持
![2021-04-09_164333](https://user-images.githubusercontent.com/16462258/114156685-69ba0280-9955-11eb-9cad-1066426212fe.png)

还修改了`kernel-3.4.x.config`以支持256m内存
![2021-04-09_162358](https://user-images.githubusercontent.com/16462258/114151749-05e10b00-9950-11eb-83df-d9a9ad5799e2.png)

只有这两处的改动, 其它多余的改动又折腾回去了

**Comment by huazhuangnan** [comment]
那应该没啥问题吧，明天我有时间，我编译一个看下，刚好有个k2在手上

**Comment by lon91ong** [comment]
有结果了吗???

**Comment by huazhuangnan** [comment]
关注下更新，这两天我就会大改！

**Comment by huazhuangnan** [comment]
已经更新

**Comment by fengyuentau** [comment]
@HuaZhuangNan 这个问题仍然存在，我刷过度盘里面的稳定归档和401最新的版本，都是无法按帖子里面写的192.168.2.1访问。反而我看给的路由器的ip是192.168.123.1，登录后有弹窗要求登录，但是root/admin/password这个组合试了都登不上。

**Comment by HuaZhuangNan** [comment]
你试过了beed刷入？

**Comment by huazhuangnan** [comment]
> @HuaZhuangNan 这个问题仍然存在，我刷过度盘里面的稳定归档和401最新的版本，都是无法按帖子里面写的192.168.2.1访问。反而我看给的路由器的ip是192.168.123.1，登录后有弹窗要求登录，但是root/admin/password这个组合试了都登不上。

试过beed刷入？
