### ISSUE TITLE
解决vssr(hello world)编译冲突

### ISSUE THREAD

**Issue by ghost** [HuaZhuangNan/actions-build-padavan-openwrt#4]
可以试试这个
https://github.com/Leo-Jo-My/luci-app-vssr-plus.git
该作者修复了vssr(hello world)跟lean大的ssr+编译冲突的问题

**Comment by huazhuangnan** [comment]
好的，我看看，感谢你反馈！

**Comment by ghost** [comment]
leo-jo-my的vssr貌似不包含luci-i18n-vssr-plus-zh-cn（不确定，但我本地make menuconfig的时候并没有找到）

**Comment by huazhuangnan** [comment]
没事，如果以后用标准的话会用的到

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/27522149/79395916-49a76b80-7fad-11ea-825a-371a82a500b5.png)
clone了两次依赖包
```bash
echo '添加Leo-Jo-My的Hello World,并且使用默认包配置'
git clone $vssr_plus_rely package/my
git clone $vssr_plus package/luci-app-vssr-plus
echo 'CONFIG_PACKAGE_luci-app-vssr-plus=y' >> .config
echo 'CONFIG_PACKAGE_luci-i18n-vssr-plus-zh-cn=y'  >> .config
```
我目前并没有测试两个插件能否共存，仅试验过将两个插件改成M后可成功编译

**Comment by huazhuangnan** [comment]
作者好像关了仓库，哈哈，等我忙完这段时间在搞吧，先不搞
