### ISSUE TITLE
chongshengB大更新了一些bug,现在花妆小哥的K2自动编译过不去了

### ISSUE THREAD

**Issue by spiderpigpig** [HuaZhuangNan/actions-build-padavan-openwrt#5]
希望小哥有空能整整,研究半天是真看不明白,C大那自动编译K2的固件会到8M以上,无法导入K2

以下C大的更新日志
##2020.04.17##

增加网易云解锁2合1（修改自雕大的源码），包含go版本和云解锁
修改SSP的gfw模式
修复SSP的v2 tcp模式
同步最新源码

**Comment by huazhuangnan** [comment]
已经修复
