### ISSUE TITLE
自动编译的压缩包无法解压

### ISSUE THREAD

**Issue by yung5133** [HuaZhuangNan/actions-build-padavan-openwrt#7]
下载了自动编译的固件压缩包无法解压，出现错误

**Comment by huazhuangnan** [comment]
具体指那个包呢？日志是否出现报错呢？能不能描述的详细点？

**Comment by huazhuangnan** [comment]
padavan可以解压，没问题，op待测试

**Comment by yung5133** [comment]
> 具体指那个包呢？日志是否出现报错呢？能不能描述的详细点？

编译的PSG1218的padavan包，下载了大佬你编译的4月17号的包同样无法在Win10下用360解压软件，提示这个压缩文件格式未知或数据已经损坏，这是我的编译地址https://github.com/lixiangyang1994/actions-build-padavan-openwrt/actions/runs/87506019

**Comment by huazhuangnan** [comment]
下载没下完全？我刚测试可以解压啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lixiangyang1994"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 中午1:20
收件人: "HuaZhuangNan/actions-build-padavan-openwrt"<actions-build-padavan-openwrt@noreply.github.com&gt;; 
抄送: "花妆男"<huazhuangnan@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HuaZhuangNan/actions-build-padavan-openwrt] 自动编译的压缩包无法解压 (#7)





  
具体指那个包呢？日志是否出现报错呢？能不能描述的详细点？
  
编译的PSG1218的padavan包，下载了大佬你编译的4月17号的包同样无法在Win10下用360解压软件，提示这个压缩文件格式未知或数据已经损坏

**Comment by yung5133** [comment]
> 下载没下完全？我刚测试可以解压啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lixiangyang1994"<notifications@github.com&gt;; 发送时间: 2020年4月26日(星期天) 中午1:20 收件人: "HuaZhuangNan/actions-build-padavan-openwrt"<actions-build-padavan-openwrt@noreply.github.com&gt;; 抄送: "花妆男"<huazhuangnan@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [HuaZhuangNan/actions-build-padavan-openwrt] 自动编译的压缩包无法解压 (#7) 具体指那个包呢？日志是否出现报错呢？能不能描述的详细点？ 编译的PSG1218的padavan包，下载了大佬你编译的4月17号的包同样无法在Win10下用360解压软件，提示这个压缩文件格式未知或数据已经损坏 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我再试试，GitHub下载速度太慢，有可能是没下完全

**Comment by huazhuangnan** [comment]
![image](https://user-images.githubusercontent.com/46070704/80299171-e0053980-87c4-11ea-9d14-c1e5830d748f.png)
刚去你仓库看了，可以解压

**Comment by yung5133** [comment]
> 下载没下完全？我刚测试可以解压啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lixiangyang1994"<notifications@github.com&gt;; 发送时间: 2020年4月26日(星期天) 中午1:20 收件人: "HuaZhuangNan/actions-build-padavan-openwrt"<actions-build-padavan-openwrt@noreply.github.com&gt;; 抄送: "花妆男"<huazhuangnan@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [HuaZhuangNan/actions-build-padavan-openwrt] 自动编译的压缩包无法解压 (#7) 具体指那个包呢？日志是否出现报错呢？能不能描述的详细点？ 编译的PSG1218的padavan包，下载了大佬你编译的4月17号的包同样无法在Win10下用360解压软件，提示这个压缩文件格式未知或数据已经损坏 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
刚刚我开启全局模式下载试了下，发现确实可以解压了，应该就是下载不完全，谢谢解答

**Comment by yung5133** [comment]
> ![image](https://user-images.githubusercontent.com/46070704/80299171-e0053980-87c4-11ea-9d14-c1e5830d748f.png)
> 刚去你仓库看了，可以解压

因为也没有md5验证以为是压缩包出问题了，确实是网络的问题
