### ISSUE TITLE
大佬，有无考虑 添加一键搭建LNMP？

### ISSUE THREAD

**Issue by lee29** [HuaZhuangNan/actions-build-padavan-openwrt#8]
rt

**Comment by huazhuangnan** [comment]
找包添加就好，不难，你要谁的一键包，发我，帮你集成下

**Comment by lee29** [comment]
> 找包添加就好，不难，你要谁的一键包，发我，帮你集成下

我也不知道哪里有包啊，比如hiboy大神的那个？cヾ(ｏ･ω･)ﾉ

**Comment by lee29** [comment]
> 找包添加就好，不难，你要谁的一键包，发我，帮你集成下

http://4pda.ru/forum/index.php?showtopic=714487   这个？好像是要构建的时候就编译进去了

**Comment by huazhuangnan** [comment]
好，明天试试

**Comment by huazhuangnan** [comment]
老毛子集成要写页面啥的不搞
